#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const groups = [
  { title: "Line Icons", dir: "assets/icons/line", note: "Default for report cards, lists, and process labels." },
  { title: "Solid Status Icons", dir: "assets/icons/solid", note: "Use only inside compact status tags and alert markers." },
  { title: "BGY Business Icons", dir: "assets/icons/bgy-business", note: "Property-management domains and operation topics." },
  { title: "Diagram SVG", dir: "assets/svg/diagrams", note: "Simple framework and process motifs." },
  { title: "Empty States", dir: "assets/svg/empty-states", note: "Honest placeholders for missing evidence or screenshots." },
  { title: "Patterns", dir: "assets/svg/patterns", note: "Restrained background/corner motifs; keep decorative only." },
];

function filesFor(dir) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs)
    .filter(name => /\.svg$/i.test(name))
    .sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }))
    .map(name => ({ name, rel: `${dir}/${name}`.replaceAll("\\", "/") }));
}

const sections = groups.map(group => {
  const cards = filesFor(group.dir).map(file => {
    const id = file.name.replace(/\.svg$/i, "");
    return `<article class="asset-card">
      <div class="icon-wrap"><img src="${file.rel}" alt="${id}"></div>
      <p class="asset-name">${id}</p>
      <p class="asset-path">${file.rel}</p>
    </article>`;
  }).join("\n");
  return `<section>
    <div class="section-head">
      <h2>${group.title}</h2>
      <p>${group.note}</p>
    </div>
    <div class="asset-grid">${cards}</div>
  </section>`;
}).join("\n");

const html = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>BGY Local Icon Gallery</title>
  <style>
    :root {
      --bgy-blue: #006D9A;
      --bgy-deep-blue: #004B6B;
      --line: #D8E3EA;
      --panel: #F5F8FA;
      --text: #1F2933;
      --muted: #64748B;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: #fff;
      color: var(--text);
      font-family: "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
    }
    header {
      padding: 32px 44px 24px;
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }
    h1 {
      margin: 0;
      color: var(--bgy-deep-blue);
      font-size: 30px;
      line-height: 1.2;
    }
    header p {
      margin: 10px 0 0;
      color: var(--muted);
      font-size: 15px;
      line-height: 1.6;
    }
    section {
      padding: 28px 44px 8px;
    }
    .section-head {
      display: flex;
      align-items: baseline;
      gap: 16px;
      margin-bottom: 14px;
    }
    h2 {
      margin: 0;
      color: var(--bgy-deep-blue);
      font-size: 21px;
    }
    .section-head p {
      margin: 0;
      color: var(--muted);
      font-size: 13px;
    }
    .asset-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
      gap: 12px;
    }
    .asset-card {
      min-height: 132px;
      border: 1px solid var(--line);
      background: #fff;
      padding: 14px;
      display: grid;
      grid-template-rows: 44px auto auto;
      gap: 8px;
      align-items: start;
    }
    .icon-wrap {
      width: 44px;
      height: 44px;
      color: var(--bgy-blue);
      display: grid;
      place-items: center;
      border-radius: 8px;
      background: #EDF7FB;
    }
    .icon-wrap img {
      width: 26px;
      height: 26px;
      color: var(--bgy-blue);
    }
    .asset-name {
      margin: 0;
      color: var(--text);
      font-size: 14px;
      font-weight: 700;
      line-height: 1.3;
    }
    .asset-path {
      margin: 0;
      color: var(--muted);
      font-size: 11px;
      line-height: 1.35;
      word-break: break-all;
    }
    footer {
      padding: 28px 44px 40px;
      color: var(--muted);
      font-size: 13px;
    }
  </style>
</head>
<body>
  <header>
    <h1>BGY Local Icon Gallery</h1>
    <p>Use these local assets for BGY PPT-bound HTML. Prefer inline SVG copied from the source files when the icon should become editable native PPT shapes.</p>
  </header>
  ${sections}
  <footer>Generated by scripts/build_icon_gallery.mjs.</footer>
</body>
</html>
`;

fs.writeFileSync(path.join(ROOT, "assets", "icon-gallery.html"), html, "utf8");
console.log("Icon gallery generated.");
